clean: true
author: Diogo Autilio
author_url: https://github.com/dogo
github_url: https://github.com/dogo/SketchKit
copyright: Copyright (c) 2020 Anykey Entertrainment. All rights reserved.
swift_build_tool: xcodebuild
module: SketchKit
xcodebuild_arguments:
   - clean
   - build
   - -scheme
   - SketchKit
   - -sdk
   - iphonesimulator
   - -destination
   - generic/platform=iOS Simulator
output: docs
