clean: true
author: Diogo Autilio
author_url: https://github.com/dogo
github_url: https://github.com/dogo/SketchKit
copyright: Copyright (c) 2026 Anykey Entertainment. All rights reserved.
theme: fullwidth
swift_build_tool: xcodebuild
module: SketchKit
xcodebuild_arguments:
   - clean
   - build
   - -scheme
   - SketchKit
   - -sdk
   - iphonesimulator
   - -destination
   - generic/platform=iOS Simulator
output: docs
custom_categories:
   - name: Layout DSL
     children:
       - Constrainable
       - SketchKitDSL
   - name: Platform Abstractions
     children:
       - View
       - LayoutGuide
       - LayoutPriority
       - EdgeInsets
