name: Publish Documentation

on: 
  release:
    types: [published]

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish Jazzy Docs
      uses: swiftpackages/jazzy-swift-docs-action@v2
      with:
        personal_access_token: ${{ secrets.JAZZY_ACCESS_TOKEN }}
